INSERT INTO scrape_queries (query) VALUES
-- ROOFERS in wealthy areas
('roofer in Newport Beach, California'),
('roofer in Irvine, California'),
('roofer in Laguna Beach, California'),
('roofer in Laguna Niguel, California'),
('roofer in Mission Viejo, California'),
('roofer in San Clemente, California'),
('roofer in Dana Point, California'),
('roofer in Aliso Viejo, California'),
('roofer in Lake Forest, California'),
('roofer in Yorba Linda, California'),
('roofer in Tustin, California'),
('roofer in Rancho Santa Margarita, California'),
('roofer in Coto de Caza, California'),
('roofer in San Juan Capistrano, California'),
('roofer in Encinitas, California'),
('roofer in Carlsbad, California'),
('roofer in Del Mar, California'),
('roofer in La Jolla, California'),
('roofer in Poway, California'),
('roofer in Rancho Bernardo, California'),
('roofer in Rancho Santa Fe, California'),
('roofer in Solana Beach, California'),
('roofer in Chula Vista, California'),
('roofer in Coronado, California'),
('roofer in Escondido, California'),
('roofer in Pasadena, California'),
('roofer in Arcadia, California'),
('roofer in San Marino, California'),
('roofer in La Canada Flintridge, California'),
('roofer in Monrovia, California'),
('roofer in Thousand Oaks, California'),
('roofer in Westlake Village, California'),
('roofer in Calabasas, California'),
('roofer in Agoura Hills, California'),
('roofer in Simi Valley, California'),
('roofer in Moorpark, California'),
('roofer in Camarillo, California'),
('roofer in Oxnard, California'),
('roofer in Ventura, California'),
('roofer in Santa Barbara, California'),
('roofer in Montecito, California'),
('roofer in Goleta, California'),
('roofer in Los Altos, California'),
('roofer in Los Altos Hills, California'),
('roofer in Saratoga, California'),
('roofer in Los Gatos, California'),
('roofer in Monte Sereno, California'),
('roofer in Cupertino, California'),
('roofer in Palo Alto, California'),
('roofer in Menlo Park, California'),
('roofer in Atherton, California'),
('roofer in Portola Valley, California'),
('roofer in Woodside, California'),
('roofer in Hillsborough, California'),
('roofer in Burlingame, California'),
('roofer in San Mateo, California'),
('roofer in Belmont, California'),
('roofer in Foster City, California'),
('roofer in Danville, California'),
('roofer in San Ramon, California'),
('roofer in Pleasanton, California'),
('roofer in Dublin, California'),
('roofer in Walnut Creek, California'),
('roofer in Lafayette, California'),
('roofer in Orinda, California'),
('roofer in Moraga, California'),
('roofer in Alamo, California'),
('roofer in Piedmont, California'),
('roofer in Marin County, California'),
('roofer in Tiburon, California'),
('roofer in Belvedere, California'),
('roofer in Mill Valley, California'),
('roofer in Sausalito, California'),
('roofer in Corte Madera, California'),
('roofer in Ross, California'),
('roofer in San Anselmo, California'),
('roofer in Kentfield, California'),
('roofer in Napa, California'),
('roofer in St Helena, California'),
('roofer in Yountville, California'),
('roofer in Sonoma, California'),
('roofer in Healdsburg, California'),
('roofer in Palm Desert, California'),
('roofer in Palm Springs, California'),
('roofer in Rancho Mirage, California'),
('roofer in Indian Wells, California'),
('roofer in La Quinta, California'),
('roofer in Temecula, California'),
('roofer in Murrieta, California'),
('roofer in Folsom, California'),
('roofer in Roseville, California'),
('roofer in El Dorado Hills, California'),
('roofer in Granite Bay, California'),
('roofer in Rocklin, California'),
('roofer in Lincoln, California'),
('roofer in Elk Grove, California'),
-- HVAC in wealthy areas
('HVAC contractor in Newport Beach, California'),
('HVAC contractor in Irvine, California'),
('HVAC contractor in Laguna Beach, California'),
('HVAC contractor in Laguna Niguel, California'),
('HVAC contractor in Mission Viejo, California'),
('HVAC contractor in San Clemente, California'),
('HVAC contractor in Dana Point, California'),
('HVAC contractor in Yorba Linda, California'),
('HVAC contractor in Aliso Viejo, California'),
('HVAC contractor in Rancho Santa Margarita, California'),
('HVAC contractor in Coto de Caza, California'),
('HVAC contractor in Encinitas, California'),
('HVAC contractor in Carlsbad, California'),
('HVAC contractor in La Jolla, California'),
('HVAC contractor in Del Mar, California'),
('HVAC contractor in Rancho Santa Fe, California'),
('HVAC contractor in Poway, California'),
('HVAC contractor in Solana Beach, California'),
('HVAC contractor in Coronado, California'),
('HVAC contractor in Pasadena, California'),
('HVAC contractor in Arcadia, California'),
('HVAC contractor in San Marino, California'),
('HVAC contractor in La Canada Flintridge, California'),
('HVAC contractor in Thousand Oaks, California'),
('HVAC contractor in Westlake Village, California'),
('HVAC contractor in Calabasas, California'),
('HVAC contractor in Agoura Hills, California'),
('HVAC contractor in Camarillo, California'),
('HVAC contractor in Ventura, California'),
('HVAC contractor in Santa Barbara, California'),
('HVAC contractor in Montecito, California'),
('HVAC contractor in Los Altos, California'),
('HVAC contractor in Saratoga, California'),
('HVAC contractor in Los Gatos, California'),
('HVAC contractor in Cupertino, California'),
('HVAC contractor in Palo Alto, California'),
('HVAC contractor in Menlo Park, California'),
('HVAC contractor in Atherton, California'),
('HVAC contractor in Woodside, California'),
('HVAC contractor in Hillsborough, California'),
('HVAC contractor in Burlingame, California'),
('HVAC contractor in San Mateo, California'),
('HVAC contractor in Danville, California'),
('HVAC contractor in San Ramon, California'),
('HVAC contractor in Pleasanton, California'),
('HVAC contractor in Walnut Creek, California'),
('HVAC contractor in Lafayette, California'),
('HVAC contractor in Orinda, California'),
('HVAC contractor in Moraga, California'),
('HVAC contractor in Alamo, California'),
('HVAC contractor in Piedmont, California'),
('HVAC contractor in Tiburon, California'),
('HVAC contractor in Mill Valley, California'),
('HVAC contractor in Sausalito, California'),
('HVAC contractor in Ross, California'),
('HVAC contractor in Napa, California'),
('HVAC contractor in St Helena, California'),
('HVAC contractor in Sonoma, California'),
('HVAC contractor in Healdsburg, California'),
('HVAC contractor in Palm Desert, California'),
('HVAC contractor in Palm Springs, California'),
('HVAC contractor in Rancho Mirage, California'),
('HVAC contractor in Indian Wells, California'),
('HVAC contractor in La Quinta, California'),
('HVAC contractor in Temecula, California'),
('HVAC contractor in Folsom, California'),
('HVAC contractor in Roseville, California'),
('HVAC contractor in El Dorado Hills, California'),
('HVAC contractor in Granite Bay, California'),
('HVAC contractor in Rocklin, California'),
('HVAC contractor in Lincoln, California'),
('HVAC contractor in Thousand Palms, California'),
-- POOL SERVICE in wealthy areas
('pool service in Newport Beach, California'),
('pool service in Irvine, California'),
('pool service in Laguna Beach, California'),
('pool service in Laguna Niguel, California'),
('pool service in Mission Viejo, California'),
('pool service in Dana Point, California'),
('pool service in San Clemente, California'),
('pool service in Yorba Linda, California'),
('pool service in Aliso Viejo, California'),
('pool service in Rancho Santa Margarita, California'),
('pool service in Coto de Caza, California'),
('pool service in San Juan Capistrano, California'),
('pool service in Encinitas, California'),
('pool service in Carlsbad, California'),
('pool service in La Jolla, California'),
('pool service in Del Mar, California'),
('pool service in Rancho Santa Fe, California'),
('pool service in Poway, California'),
('pool service in Solana Beach, California'),
('pool service in Coronado, California'),
('pool service in Chula Vista, California'),
('pool service in Pasadena, California'),
('pool service in Arcadia, California'),
('pool service in San Marino, California'),
('pool service in La Canada Flintridge, California'),
('pool service in Thousand Oaks, California'),
('pool service in Westlake Village, California'),
('pool service in Calabasas, California'),
('pool service in Agoura Hills, California'),
('pool service in Camarillo, California'),
('pool service in Ventura, California'),
('pool service in Santa Barbara, California'),
('pool service in Montecito, California'),
('pool service in Goleta, California'),
('pool service in Los Altos, California'),
('pool service in Saratoga, California'),
('pool service in Los Gatos, California'),
('pool service in Cupertino, California'),
('pool service in Palo Alto, California'),
('pool service in Menlo Park, California'),
('pool service in Atherton, California'),
('pool service in Woodside, California'),
('pool service in Hillsborough, California'),
('pool service in Burlingame, California'),
('pool service in San Mateo, California'),
('pool service in Danville, California'),
('pool service in San Ramon, California'),
('pool service in Pleasanton, California'),
('pool service in Walnut Creek, California'),
('pool service in Lafayette, California'),
('pool service in Orinda, California'),
('pool service in Alamo, California'),
('pool service in Tiburon, California'),
('pool service in Mill Valley, California'),
('pool service in Napa, California'),
('pool service in St Helena, California'),
('pool service in Sonoma, California'),
('pool service in Healdsburg, California'),
('pool service in Palm Desert, California'),
('pool service in Palm Springs, California'),
('pool service in Rancho Mirage, California'),
('pool service in Indian Wells, California'),
('pool service in La Quinta, California'),
('pool service in Temecula, California'),
('pool service in Murrieta, California'),
('pool service in Folsom, California'),
('pool service in Roseville, California'),
('pool service in El Dorado Hills, California'),
('pool service in Granite Bay, California'),
('pool service in Rocklin, California'),
('pool service in Bel Air, California'),
('pool service in Beverly Hills, California'),
('pool service in Brentwood, California'),
('pool service in Pacific Palisades, California'),
('pool service in Malibu, California'),
('pool service in Encino, California'),
('pool service in Sherman Oaks, California'),
('pool service in Studio City, California'),
('pool service in Tarzana, California'),
('pool service in Woodland Hills, California'),
-- POOL BUILDER in wealthy areas
('pool builder in Newport Beach, California'),
('pool builder in Irvine, California'),
('pool builder in Laguna Beach, California'),
('pool builder in Yorba Linda, California'),
('pool builder in Thousand Oaks, California'),
('pool builder in Westlake Village, California'),
('pool builder in Calabasas, California'),
('pool builder in La Jolla, California'),
('pool builder in Rancho Santa Fe, California'),
('pool builder in Encinitas, California'),
('pool builder in Carlsbad, California'),
('pool builder in Poway, California'),
('pool builder in Pasadena, California'),
('pool builder in Arcadia, California'),
('pool builder in Santa Barbara, California'),
('pool builder in Montecito, California'),
('pool builder in Saratoga, California'),
('pool builder in Los Gatos, California'),
('pool builder in Danville, California'),
('pool builder in Alamo, California'),
('pool builder in Walnut Creek, California'),
('pool builder in Palm Desert, California'),
('pool builder in Palm Springs, California'),
('pool builder in Rancho Mirage, California'),
('pool builder in Indian Wells, California'),
('pool builder in La Quinta, California'),
('pool builder in Temecula, California'),
('pool builder in El Dorado Hills, California'),
('pool builder in Granite Bay, California'),
('pool builder in Bel Air, California'),
('pool builder in Beverly Hills, California'),
('pool builder in Pacific Palisades, California'),
('pool builder in Malibu, California'),
('pool builder in Encino, California'),
('pool builder in Woodland Hills, California'),
-- AUTO BODY in wealthy areas
('auto body shop in Newport Beach, California'),
('auto body shop in Irvine, California'),
('auto body shop in Laguna Beach, California'),
('auto body shop in Laguna Niguel, California'),
('auto body shop in Mission Viejo, California'),
('auto body shop in Yorba Linda, California'),
('auto body shop in Carlsbad, California'),
('auto body shop in Encinitas, California'),
('auto body shop in La Jolla, California'),
('auto body shop in Poway, California'),
('auto body shop in Rancho Bernardo, California'),
('auto body shop in Pasadena, California'),
('auto body shop in Arcadia, California'),
('auto body shop in Thousand Oaks, California'),
('auto body shop in Westlake Village, California'),
('auto body shop in Calabasas, California'),
('auto body shop in Camarillo, California'),
('auto body shop in Ventura, California'),
('auto body shop in Santa Barbara, California'),
('auto body shop in Saratoga, California'),
('auto body shop in Los Gatos, California'),
('auto body shop in Cupertino, California'),
('auto body shop in Los Altos, California'),
('auto body shop in Palo Alto, California'),
('auto body shop in Menlo Park, California'),
('auto body shop in Burlingame, California'),
('auto body shop in San Mateo, California'),
('auto body shop in Danville, California'),
('auto body shop in San Ramon, California'),
('auto body shop in Pleasanton, California'),
('auto body shop in Walnut Creek, California'),
('auto body shop in Lafayette, California'),
('auto body shop in Orinda, California'),
('auto body shop in Tiburon, California'),
('auto body shop in Mill Valley, California'),
('auto body shop in Napa, California'),
('auto body shop in Sonoma, California'),
('auto body shop in Palm Desert, California'),
('auto body shop in Palm Springs, California'),
('auto body shop in Rancho Mirage, California'),
('auto body shop in Temecula, California'),
('auto body shop in Folsom, California'),
('auto body shop in Roseville, California'),
('auto body shop in El Dorado Hills, California'),
('auto body shop in Granite Bay, California'),
('auto body shop in Beverly Hills, California'),
('auto body shop in Brentwood, California'),
('auto body shop in Pacific Palisades, California'),
('auto body shop in Malibu, California'),
('auto body shop in Encino, California'),
-- LANDSCAPER in wealthy areas
('landscaper in Newport Beach, California'),
('landscaper in Irvine, California'),
('landscaper in Laguna Beach, California'),
('landscaper in Laguna Niguel, California'),
('landscaper in Mission Viejo, California'),
('landscaper in San Clemente, California'),
('landscaper in Dana Point, California'),
('landscaper in Yorba Linda, California'),
('landscaper in Aliso Viejo, California'),
('landscaper in Rancho Santa Margarita, California'),
('landscaper in Coto de Caza, California'),
('landscaper in San Juan Capistrano, California'),
('landscaper in Encinitas, California'),
('landscaper in Carlsbad, California'),
('landscaper in La Jolla, California'),
('landscaper in Del Mar, California'),
('landscaper in Rancho Santa Fe, California'),
('landscaper in Poway, California'),
('landscaper in Solana Beach, California'),
('landscaper in Coronado, California'),
('landscaper in Pasadena, California'),
('landscaper in Arcadia, California'),
('landscaper in San Marino, California'),
('landscaper in La Canada Flintridge, California'),
('landscaper in Thousand Oaks, California'),
('landscaper in Westlake Village, California'),
('landscaper in Calabasas, California'),
('landscaper in Agoura Hills, California'),
('landscaper in Camarillo, California'),
('landscaper in Ventura, California'),
('landscaper in Santa Barbara, California'),
('landscaper in Montecito, California'),
('landscaper in Goleta, California'),
('landscaper in Los Altos, California'),
('landscaper in Los Altos Hills, California'),
('landscaper in Saratoga, California'),
('landscaper in Los Gatos, California'),
('landscaper in Cupertino, California'),
('landscaper in Palo Alto, California'),
('landscaper in Menlo Park, California'),
('landscaper in Atherton, California'),
('landscaper in Portola Valley, California'),
('landscaper in Woodside, California'),
('landscaper in Hillsborough, California'),
('landscaper in Burlingame, California'),
('landscaper in San Mateo, California'),
('landscaper in Danville, California'),
('landscaper in San Ramon, California'),
('landscaper in Pleasanton, California'),
('landscaper in Walnut Creek, California'),
('landscaper in Lafayette, California'),
('landscaper in Orinda, California'),
('landscaper in Moraga, California'),
('landscaper in Alamo, California'),
('landscaper in Piedmont, California'),
('landscaper in Tiburon, California'),
('landscaper in Belvedere, California'),
('landscaper in Mill Valley, California'),
('landscaper in Sausalito, California'),
('landscaper in Ross, California'),
('landscaper in Kentfield, California'),
('landscaper in Napa, California'),
('landscaper in St Helena, California'),
('landscaper in Yountville, California'),
('landscaper in Sonoma, California'),
('landscaper in Healdsburg, California'),
('landscaper in Palm Desert, California'),
('landscaper in Palm Springs, California'),
('landscaper in Rancho Mirage, California'),
('landscaper in Indian Wells, California'),
('landscaper in La Quinta, California'),
('landscaper in Temecula, California'),
('landscaper in Murrieta, California'),
('landscaper in Folsom, California'),
('landscaper in Roseville, California'),
('landscaper in El Dorado Hills, California'),
('landscaper in Granite Bay, California'),
('landscaper in Rocklin, California'),
('landscaper in Bel Air, California'),
('landscaper in Beverly Hills, California'),
('landscaper in Brentwood, California'),
('landscaper in Pacific Palisades, California'),
('landscaper in Malibu, California'),
('landscaper in Encino, California'),
('landscaper in Sherman Oaks, California'),
('landscaper in Studio City, California'),
('landscaper in Tarzana, California'),
('landscaper in Woodland Hills, California'),
-- ROOFER LA wealthy neighborhoods
('roofer in Bel Air, California'),
('roofer in Beverly Hills, California'),
('roofer in Brentwood, California'),
('roofer in Pacific Palisades, California'),
('roofer in Malibu, California'),
('roofer in Encino, California'),
('roofer in Sherman Oaks, California'),
('roofer in Studio City, California'),
('roofer in Tarzana, California'),
('roofer in Woodland Hills, California'),
('roofer in Northridge, California'),
('roofer in Granada Hills, California'),
('roofer in Porter Ranch, California'),
('roofer in Chatsworth, California'),
('roofer in West Hills, California'),
-- CONCRETE in wealthy areas
('concrete contractor in Newport Beach, California'),
('concrete contractor in Irvine, California'),
('concrete contractor in Laguna Beach, California'),
('concrete contractor in Yorba Linda, California'),
('concrete contractor in Thousand Oaks, California'),
('concrete contractor in Westlake Village, California'),
('concrete contractor in Calabasas, California'),
('concrete contractor in La Jolla, California'),
('concrete contractor in Rancho Santa Fe, California'),
('concrete contractor in Encinitas, California'),
('concrete contractor in Carlsbad, California'),
('concrete contractor in Poway, California'),
('concrete contractor in Pasadena, California'),
('concrete contractor in Arcadia, California'),
('concrete contractor in Santa Barbara, California'),
('concrete contractor in Montecito, California'),
('concrete contractor in Saratoga, California'),
('concrete contractor in Los Gatos, California'),
('concrete contractor in Palo Alto, California'),
('concrete contractor in Menlo Park, California'),
('concrete contractor in Atherton, California'),
('concrete contractor in Danville, California'),
('concrete contractor in Alamo, California'),
('concrete contractor in Walnut Creek, California'),
('concrete contractor in Tiburon, California'),
('concrete contractor in Mill Valley, California'),
('concrete contractor in Napa, California'),
('concrete contractor in Sonoma, California'),
('concrete contractor in Palm Desert, California'),
('concrete contractor in Palm Springs, California'),
('concrete contractor in Rancho Mirage, California'),
('concrete contractor in Temecula, California'),
('concrete contractor in El Dorado Hills, California'),
('concrete contractor in Granite Bay, California'),
('concrete contractor in Beverly Hills, California'),
('concrete contractor in Pacific Palisades, California'),
('concrete contractor in Malibu, California'),
('concrete contractor in Encino, California'),
('concrete contractor in Woodland Hills, California'),
-- TREE SERVICE in wealthy areas
('tree service in Newport Beach, California'),
('tree service in Irvine, California'),
('tree service in Laguna Beach, California'),
('tree service in Laguna Niguel, California'),
('tree service in Mission Viejo, California'),
('tree service in Yorba Linda, California'),
('tree service in Encinitas, California'),
('tree service in Carlsbad, California'),
('tree service in La Jolla, California'),
('tree service in Rancho Santa Fe, California'),
('tree service in Poway, California'),
('tree service in Pasadena, California'),
('tree service in Arcadia, California'),
('tree service in San Marino, California'),
('tree service in La Canada Flintridge, California'),
('tree service in Thousand Oaks, California'),
('tree service in Westlake Village, California'),
('tree service in Calabasas, California'),
('tree service in Camarillo, California'),
('tree service in Santa Barbara, California'),
('tree service in Montecito, California'),
('tree service in Los Altos, California'),
('tree service in Saratoga, California'),
('tree service in Los Gatos, California'),
('tree service in Palo Alto, California'),
('tree service in Menlo Park, California'),
('tree service in Atherton, California'),
('tree service in Woodside, California'),
('tree service in Hillsborough, California'),
('tree service in Danville, California'),
('tree service in Alamo, California'),
('tree service in Walnut Creek, California'),
('tree service in Lafayette, California'),
('tree service in Orinda, California'),
('tree service in Piedmont, California'),
('tree service in Tiburon, California'),
('tree service in Mill Valley, California'),
('tree service in Ross, California'),
('tree service in Napa, California'),
('tree service in St Helena, California'),
('tree service in Sonoma, California'),
('tree service in Healdsburg, California'),
('tree service in Palm Desert, California'),
('tree service in Palm Springs, California'),
('tree service in Rancho Mirage, California'),
('tree service in El Dorado Hills, California'),
('tree service in Granite Bay, California'),
('tree service in Bel Air, California'),
('tree service in Beverly Hills, California'),
('tree service in Brentwood, California'),
('tree service in Pacific Palisades, California'),
('tree service in Malibu, California'),
('tree service in Encino, California'),
-- PLUMBER in wealthy areas
('plumber in Newport Beach, California'),
('plumber in Irvine, California'),
('plumber in Laguna Beach, California'),
('plumber in Laguna Niguel, California'),
('plumber in Mission Viejo, California'),
('plumber in Yorba Linda, California'),
('plumber in Encinitas, California'),
('plumber in Carlsbad, California'),
('plumber in La Jolla, California'),
('plumber in Rancho Santa Fe, California'),
('plumber in Poway, California'),
('plumber in Coronado, California'),
('plumber in Pasadena, California'),
('plumber in Arcadia, California'),
('plumber in San Marino, California'),
('plumber in La Canada Flintridge, California'),
('plumber in Thousand Oaks, California'),
('plumber in Westlake Village, California'),
('plumber in Calabasas, California'),
('plumber in Camarillo, California'),
('plumber in Santa Barbara, California'),
('plumber in Montecito, California'),
('plumber in Los Altos, California'),
('plumber in Saratoga, California'),
('plumber in Los Gatos, California'),
('plumber in Cupertino, California'),
('plumber in Palo Alto, California'),
('plumber in Menlo Park, California'),
('plumber in Atherton, California'),
('plumber in Woodside, California'),
('plumber in Hillsborough, California'),
('plumber in Burlingame, California'),
('plumber in Danville, California'),
('plumber in San Ramon, California'),
('plumber in Pleasanton, California'),
('plumber in Walnut Creek, California'),
('plumber in Lafayette, California'),
('plumber in Orinda, California'),
('plumber in Alamo, California'),
('plumber in Tiburon, California'),
('plumber in Mill Valley, California'),
('plumber in Sausalito, California'),
('plumber in Ross, California'),
('plumber in Napa, California'),
('plumber in St Helena, California'),
('plumber in Sonoma, California'),
('plumber in Healdsburg, California'),
('plumber in Palm Desert, California'),
('plumber in Palm Springs, California'),
('plumber in Rancho Mirage, California'),
('plumber in Indian Wells, California'),
('plumber in La Quinta, California'),
('plumber in Temecula, California'),
('plumber in El Dorado Hills, California'),
('plumber in Granite Bay, California'),
('plumber in Bel Air, California'),
('plumber in Beverly Hills, California'),
('plumber in Brentwood, California'),
('plumber in Pacific Palisades, California'),
('plumber in Malibu, California'),
('plumber in Encino, California'),
-- ELECTRICIAN in wealthy areas
('electrician in Newport Beach, California'),
('electrician in Irvine, California'),
('electrician in Laguna Beach, California'),
('electrician in Yorba Linda, California'),
('electrician in Thousand Oaks, California'),
('electrician in Westlake Village, California'),
('electrician in Calabasas, California'),
('electrician in La Jolla, California'),
('electrician in Rancho Santa Fe, California'),
('electrician in Encinitas, California'),
('electrician in Carlsbad, California'),
('electrician in Poway, California'),
('electrician in Pasadena, California'),
('electrician in Arcadia, California'),
('electrician in San Marino, California'),
('electrician in Santa Barbara, California'),
('electrician in Montecito, California'),
('electrician in Los Altos, California'),
('electrician in Saratoga, California'),
('electrician in Los Gatos, California'),
('electrician in Palo Alto, California'),
('electrician in Menlo Park, California'),
('electrician in Atherton, California'),
('electrician in Woodside, California'),
('electrician in Hillsborough, California'),
('electrician in Danville, California'),
('electrician in Alamo, California'),
('electrician in Walnut Creek, California'),
('electrician in Lafayette, California'),
('electrician in Orinda, California'),
('electrician in Tiburon, California'),
('electrician in Mill Valley, California'),
('electrician in Ross, California'),
('electrician in Napa, California'),
('electrician in St Helena, California'),
('electrician in Sonoma, California'),
('electrician in Palm Desert, California'),
('electrician in Palm Springs, California'),
('electrician in Rancho Mirage, California'),
('electrician in El Dorado Hills, California'),
('electrician in Granite Bay, California'),
('electrician in Beverly Hills, California'),
('electrician in Pacific Palisades, California'),
('electrician in Malibu, California'),
('electrician in Encino, California'),
('electrician in Brentwood, California'),
-- PEST CONTROL in wealthy areas
('pest control in Newport Beach, California'),
('pest control in Irvine, California'),
('pest control in Laguna Beach, California'),
('pest control in Yorba Linda, California'),
('pest control in Thousand Oaks, California'),
('pest control in Westlake Village, California'),
('pest control in Calabasas, California'),
('pest control in La Jolla, California'),
('pest control in Rancho Santa Fe, California'),
('pest control in Encinitas, California'),
('pest control in Carlsbad, California'),
('pest control in Poway, California'),
('pest control in Pasadena, California'),
('pest control in Arcadia, California'),
('pest control in Santa Barbara, California'),
('pest control in Montecito, California'),
('pest control in Saratoga, California'),
('pest control in Los Gatos, California'),
('pest control in Palo Alto, California'),
('pest control in Menlo Park, California'),
('pest control in Atherton, California'),
('pest control in Danville, California'),
('pest control in Alamo, California'),
('pest control in Walnut Creek, California'),
('pest control in Lafayette, California'),
('pest control in Orinda, California'),
('pest control in Tiburon, California'),
('pest control in Mill Valley, California'),
('pest control in Napa, California'),
('pest control in Sonoma, California'),
('pest control in Palm Desert, California'),
('pest control in Palm Springs, California'),
('pest control in Rancho Mirage, California'),
('pest control in El Dorado Hills, California'),
('pest control in Granite Bay, California'),
('pest control in Beverly Hills, California'),
('pest control in Pacific Palisades, California'),
('pest control in Malibu, California'),
('pest control in Encino, California'),
('pest control in Brentwood, California')
ON CONFLICT (query) DO NOTHING;
